### PR TITLE
Functionality to pause game added

### PR DESCRIPTION
**Pull request by amarlearning**
one
two
three

### CODE REVIEW

**Comment by prodicus** [comment]
Hey @amarlearning 

Have you tested it on *nix based systems?

**Comment by amarlearning** [comment]
@prodicus No. I haven't tested it on *nix system. But i am pretty sure that it will work fine.

**Comment by prodicus** [comment]
@amarlearning Would be great if you could test it

**Comment by amarlearning** [comment]
@prodicus I don't have any *nix os installed in my system. will you please check this ?
clone link : https://github.com/amarlearning/spaceShooter.git

**Comment by amarlearning** [comment]
@prodicus  
imageedit_2_8636352151
imageedit_4_8127401724
imageedit_6_6626268900

**Comment by amarlearning** [comment]
@prodicus ??

**Pull request closed without merging**
